Allow hooks on sd
Will refactor everything to allow hooks later.
This should also allow per-language hooks and other treats.

diff --git a/sd b/sd
--- a/sd
+++ b/sd
@@ -3,45 +3,43 @@ IAMAT=$(dirname $0)
 source $IAMAT/base
 
 sd () {
-    # Find matching target
-    if [ -z "$1" ]
-    then
-        # run at without args, go to $PROJ_DIR
-        if [ ! -z "$VIRTUAL_ENV" ]; then
-            deactivate
-        fi
-        pushd $PROJ_DIR > /dev/null
-        return 0
-    fi
 
-    if [ ! -d "$PROJ_DIR/$1" ]
-    then
-        # Target not found, looking for aliases
-        if [ -e "$PROJ_FILE" ]; then
-            source $PROJ_FILE
-        else
-            echo "Unable to find '.projcd' alias file" >> /dev/stderr
-            return -1
-        fi
-        [ ${name_alias[$1]+1} ] && TGT=${name_alias[$1]} || (echo "Alias not found" >> /dev/stderr && return -1)
-    # Target is a directory
+  # Exec pre hooks
+  for HOOK in $SWISSKNIFE_PRE_SD_HOOKS; do
+    eval _pre_sd_${HOOK}_hook
+  done
+
+  # Find matching target
+  if [ -z "$1" ]; then
+
+    # Go to home if none
+    pushd $PROJ_DIR > /dev/null
+
+  elif [ ! -d "$PROJ_DIR/$1" ]; then
+
+    # Target not found, looking for aliases
+    if [ -e "$PROJ_FILE" ]; then
+      source $PROJ_FILE
     else
-        TGT=$1
+      echo "Unable to find '.projcd' alias file" >> /dev/stderr
+      return -1
     fi
 
-    # Check if target exists
-    if [ ! -e "$PROJ_DIR/$TGT" ]; then; echo "Target directory not found" >> /dev/stderr && return -1; fi
+    [ ${name_alias[$1]+1} ] && TGT=${name_alias[$1]} || (echo "Alias not found" >> /dev/stderr && return -1)
+  else
+    TGT=$1
+  fi
 
-    # Leave current virtualenv, if any
-    if [ ! -z "$VIRTUAL_ENV" ]; then
-        deactivate
-    fi
+  # Check if target exists
+  if [ ! -e "$PROJ_DIR/$TGT" ]; then; echo "Target directory not found" >> /dev/stderr && return -1; fi
 
-    # Force directory change
-    pushd $PROJ_DIR/$TGT > /dev/null
+  # Force directory change
+  pushd $PROJ_DIR/$TGT > /dev/null
 
-    # If file exists (thus a python project)
-    if [ -e "$VENV_STR" ]; then
-        source $VENV_STR
-    fi
+
+  for HOOK in $SWISSKNIFE_POST_SD_HOOKS; do
+    eval _post_sd_${HOOK}_hook
+  done
+
+  return 0
 }
